name: Build Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub's Linux VM
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x, 24.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: sudo apt-get install -y build-essential
      - run: npm install
